# https://cert-manager.io/docs/concepts/ca-injector/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: resource-memutator-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resource-memutator-webhook-tls
spec:
  secretName: resource-memutator-webhook-tls-secret
  commonName: resource-memutator-webhook-svc.default.svc
  dnsNames:
    - resource-memutator-webhook-svc.default.svc
  issuerRef:
    name: resource-memutator-selfsigned-issuer
    kind: Issuer
