# https://cert-manager.io/docs/concepts/ca-injector/
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-memutator-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/resource-memutator-webhook-tls # annotations for Injection
webhooks:
  - name: resource-memutator.k8s.io
    clientConfig:
      service:
        name: resource-memutator-webhook-svc
        namespace: default
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
