apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-memutator-webhook
  labels:
    app: resource-memutator-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-memutator-webhook
  template:
    metadata:
      labels:
        app: resource-memutator-webhook
    spec:
      containers:
      - name: webhook
        image: resource-memutator:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: /Certificate
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: resource-memutator-webhook-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: resource-memutator-webhook-svc
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: resource-memutator-webhook
