apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox-statefulset
  name: kube-system
spec:
  serviceName: "busybox-service"
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "3600"
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: busybox-volume
          mountPath: /mnt/data
  volumeClaimTemplates:
  - metadata:
      name: busybox-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
